apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netobserv

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - cm.yaml
  - pod.yaml
  - pvc.yaml
  - service.yaml
