apiVersion: flows.netobserv.io/v1alpha1
kind: FlowCollector
metadata:
  name: cluster
spec:
  agent: ipfix
  clusterNetworkOperator:
    namespace: openshift-network-operator
  consolePlugin:
    image: quay.io/netobserv/network-observability-console-plugin:main
    imagePullPolicy: IfNotPresent
    logLevel: info
    port: 9001
    portNaming:
      enable: true
      portNames:
        "3100": loki
    register: true
    replicas: 1
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 50Mi
  ebpf:
    cacheActiveTimeout: 5s
    cacheMaxFlows: 1000
    excludeInterfaces:
    - lo
    image: quay.io/netobserv/netobserv-ebpf-agent:main
    imagePullPolicy: IfNotPresent
    interfaces: []
    logLevel: info
    privileged: false
    resources: {}
    sampling: 0
  flowlogsPipeline:
    enableKubeProbes: true
    healthPort: 8080
    image: quay.io/netobserv/flowlogs-pipeline:main
    imagePullPolicy: IfNotPresent
    kind: DaemonSet
    logLevel: info
    port: 2055
    prometheusPort: 9090
    replicas: 1
    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi
  ipfix:
    cacheActiveTimeout: 60s
    cacheMaxFlows: 100
    sampling: 400
  kafka:
    address: kafka-cluster-kafka-bootstrap.network-observability
    enable: false
    topic: network-flows
  loki:
    batchSize: 102400
    batchWait: 1s
    maxBackoff: 300s
    maxRetries: 10
    minBackoff: 1s
    staticLabels:
      app: netobserv-flowcollector
    timeout: 10s
    url: http://loki:3100/
  namespace: network-observability
  ovnKubernetes:
    containerName: ovnkube-node
    daemonSetName: ovnkube-node
    namespace: ovn-kubernetes

