apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signed-pipelines-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: workshop
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sign-images/manifests/
    repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-gitops/
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
