apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafana-datasources
  namespace: network-observability
spec:
  datasources:
    - access: proxy
      isDefault: true
      name: loki
      type: loki
      url: 'http://loki:3100'
      version: 1
  name: loki