apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-observability-operators
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: netobserv/netobsv-operator-apps/
    repoURL: https://github.com/rcarrata/ocp4-network-security
    targetRevision: netobserv
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true