kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-operators

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: netobserv-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'latest'
