kind: EgressNetworkPolicy
apiVersion: network.openshift.io/v1
metadata:
  name: default
spec:
  egress:
  - type: Allow
    to:
      cidrSelector: 1.1.1.1/32
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0