kind: EgressNetworkPolicy
apiVersion: network.openshift.io/v1
metadata:
  name: pepe
spec:
  egress:
  - type: Allow
    to:
      cidrSelector: 8.8.8.8/32
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0