apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-push-signed
  namespace: acs-pipeline
  labels:
    tekton.dev/pipeline: build-and-push-signed
spec:
  params:
    - name: deployment-name
      value: pipelines-vote-api
    - name: git-url
      value: 'https://github.com/hyarlaga07/pipelines-vote-api.git'
    - name: git-revision
      value: master
    - name: IMAGE
      value: 'quay-gwz7n.apps.cluster-gwz7n.sandbox2622.opentlc.com/quayadmin/pipelines-vote-api:v4'
    - name: namespace
      value: acs-pipeline
  pipelineRef:
    name: build-and-push-signed
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: source-pvc
