apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netobserv

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - grafana-ds.yaml
  - grafana-netobsv-dashboard.yaml
  - ../base
